// generated by tools/live2jsx.py
export const routes = {
  '/industries/creator-economy-payments/': () => import('./IndustriesCreatorEconomyPaymentsPage.jsx'),
  '/industries/dating-app-payments/': () => import('./IndustriesDatingAppPaymentsPage.jsx'),
  '/industries/digital-entertainment/': () => import('./IndustriesDigitalEntertainmentPage.jsx'),
  '/industries/esim-digital-utility-payments/': () => import('./IndustriesEsimDigitalUtilityPaymentsPage.jsx'),
  '/industries/learning-management-system-payments/': () => import('./IndustriesLearningManagementSystemPaymentsPage.jsx'),
  '/industries/online-gaming-payments/': () => import('./IndustriesOnlineGamingPaymentsPage.jsx'),
  '/pricing/': () => import('./PricingPage.jsx'),
  '/product/coda-consumer-platforms/': () => import('./ProductCodaConsumerPlatformsPage.jsx'),
  '/product/coda-giftcloud/': () => import('./ProductCodaGiftcloudPage.jsx'),
  '/product/coda-links/': () => import('./ProductCodaLinksPage.jsx'),
  '/product/coda-webstore/': () => import('./ProductCodaWebstorePage.jsx'),
  '/product/codapay/': () => import('./ProductCodapayPage.jsx'),
  '/product/distribution/': () => import('./ProductDistributionPage.jsx'),
  '/use-case/merchant-of-record/': () => import('./UseCaseMerchantOfRecordPage.jsx'),
}
